spring.application.name=task-manager-api
jwt.secret=xJmrtCbx9+/IrYWDicnvoDujcdyAd0OBkiG6pmerYfimqFPhs+inDoSGOV7ProtZguyxIug5N7wx/1x6VH3Wuw==
jwt.expiration=15000
jwt.refresh-expiration=604800000

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized

info.app.name=Task Manager API
info.app.description=API REST para gerenciamento de tarefas com autenticacao JWT
info.app.version=1.0.0

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile