spring.application.name=task-manager-api
jwt.secret=xJmrtCbx9+/IrYWDicnvoDujcdyAd0OBkiG6pmerYfimqFPhs+inDoSGOV7ProtZguyxIug5N7wx/1x6VH3Wuw==
jwt.expiration=900000
jwt.refresh-expiration=604800000

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized

info.app.name=Task Manager API
info.app.description=API REST para gerenciamento de tarefas com autenticacao JWT
info.app.version=1.0.0
