spring.datasource.url=jdbc:postgresql://localhost:5433/taskmanager
spring.datasource.username=taskmanager_user
spring.datasource.password=taskmanager_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
