name: CI - Build e Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Dar permissao de execucao ao Maven Wrapper
        run: chmod +x mvnw

      - name: Rodar testes
        run: ./mvnw test

      - name: Build da aplicacao
        run: ./mvnw clean package -DskipTests
